#!/usr/bin/env bash
# Installs Nginx, sets up a custom index page, and ensures it's listening on port 80
# Update the package list
apt-get update -y
# Install Nginx without prompting
apt-get install -y nginx
# Write custom content to the default Nginx root page
echo "Holberton School for the win!" > /var/www/html/index.html
# Restart Nginx without using systemctl
/etc/init.d/nginx restart
